/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeteria;
import javax.swing.JOptionPane;
/**
 *
 * @author 22PROGB04
 */
public class Menu extends javax.swing.JFrame {
    int TPagar = 0;

    int PMacchiato = 0;
    int PFrape = 0;
    int PTé = 0;
    int PCapuchino = 0;
    int PLate = 0;
    int PFrapuchino = 0;
    
    int PCroissant = 0;
    int PDona = 0;
    int PCheeseCake = 0;
    int PPayManzana = 0;
    int PBrownie = 0;
    int PFlan = 0;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        lblAcompañamientos = new javax.swing.JLabel();
        chbMacchiato = new javax.swing.JCheckBox();
        chbFrape = new javax.swing.JCheckBox();
        chbTé = new javax.swing.JCheckBox();
        chbCapuchino = new javax.swing.JCheckBox();
        chbCaféLate = new javax.swing.JCheckBox();
        chbFrapuchino = new javax.swing.JCheckBox();
        chbCroissant = new javax.swing.JCheckBox();
        chbDonaConJalea = new javax.swing.JCheckBox();
        chbCheeseCake = new javax.swing.JCheckBox();
        chbPayDeManzana = new javax.swing.JCheckBox();
        chbBrownie = new javax.swing.JCheckBox();
        chbFlan = new javax.swing.JCheckBox();
        lblAgradecimiento = new javax.swing.JLabel();
        lblSonrisa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbCalcularTotal = new javax.swing.JRadioButton();
        rbFinalizar = new javax.swing.JRadioButton();
        rbReset = new javax.swing.JRadioButton();
        txtTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        lblLogo.setBackground(new java.awt.Color(255, 0, 0));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/Logo_cafe.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblMenu.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("MENÙ");

        lblBebidas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBebidas.setForeground(new java.awt.Color(255, 255, 255));
        lblBebidas.setText("Bebidas");

        lblAcompañamientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAcompañamientos.setForeground(new java.awt.Color(255, 255, 255));
        lblAcompañamientos.setText("Acompañamientos");

        buttonGroup2.add(chbMacchiato);
        chbMacchiato.setForeground(new java.awt.Color(255, 255, 255));
        chbMacchiato.setText("Macchiato            35$");
        chbMacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMacchiatoActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbFrape);
        chbFrape.setForeground(new java.awt.Color(255, 255, 255));
        chbFrape.setText("Frape                     32$");
        chbFrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFrapeActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbTé);
        chbTé.setForeground(new java.awt.Color(255, 255, 255));
        chbTé.setText("Té                          20$");
        chbTé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTéActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbCapuchino);
        chbCapuchino.setForeground(new java.awt.Color(255, 255, 255));
        chbCapuchino.setText("Capuchino           35$");
        chbCapuchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCapuchinoActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbCaféLate);
        chbCaféLate.setForeground(new java.awt.Color(255, 255, 255));
        chbCaféLate.setText("Café Late              35$");
        chbCaféLate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCaféLateActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbFrapuchino);
        chbFrapuchino.setForeground(new java.awt.Color(255, 255, 255));
        chbFrapuchino.setText("Frapuchino          35$");
        chbFrapuchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFrapuchinoActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbCroissant);
        chbCroissant.setForeground(new java.awt.Color(255, 255, 255));
        chbCroissant.setText("Croissant                        30$");
        chbCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCroissantActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbDonaConJalea);
        chbDonaConJalea.setForeground(new java.awt.Color(255, 255, 255));
        chbDonaConJalea.setText("Dona con jalea              25$");
        chbDonaConJalea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDonaConJaleaActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbCheeseCake);
        chbCheeseCake.setForeground(new java.awt.Color(255, 255, 255));
        chbCheeseCake.setText("Cheese cake                  30$");
        chbCheeseCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCheeseCakeActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbPayDeManzana);
        chbPayDeManzana.setForeground(new java.awt.Color(255, 255, 255));
        chbPayDeManzana.setText("Pay de manzana           25$");
        chbPayDeManzana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPayDeManzanaActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbBrownie);
        chbBrownie.setForeground(new java.awt.Color(255, 255, 255));
        chbBrownie.setText("Brownie de chocolate  30$");
        chbBrownie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbBrownieActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbFlan);
        chbFlan.setForeground(new java.awt.Color(255, 255, 255));
        chbFlan.setText("Flan                                15$");
        chbFlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFlanActionPerformed(evt);
            }
        });

        lblAgradecimiento.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblAgradecimiento.setForeground(new java.awt.Color(255, 51, 51));
        lblAgradecimiento.setText("¡Gracias por su preferencia!");

        lblSonrisa.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblSonrisa.setForeground(new java.awt.Color(255, 51, 51));
        lblSonrisa.setText(":)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbMacchiato)
                            .addComponent(lblAcompañamientos)
                            .addComponent(chbFrape)
                            .addComponent(chbTé)
                            .addComponent(chbCapuchino)
                            .addComponent(chbCaféLate)
                            .addComponent(chbFrapuchino)
                            .addComponent(chbCroissant)
                            .addComponent(chbDonaConJalea)
                            .addComponent(chbCheeseCake)
                            .addComponent(chbPayDeManzana)
                            .addComponent(chbBrownie)
                            .addComponent(chbFlan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblBebidas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMenu)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAgradecimiento)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblSonrisa)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(33, 33, 33)
                .addComponent(lblBebidas)
                .addGap(18, 18, 18)
                .addComponent(chbMacchiato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFrape)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbTé)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbCapuchino)
                .addGap(7, 7, 7)
                .addComponent(chbCaféLate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFrapuchino)
                .addGap(1, 1, 1)
                .addComponent(lblAcompañamientos)
                .addGap(18, 18, 18)
                .addComponent(chbCroissant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbDonaConJalea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbCheeseCake)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbPayDeManzana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbBrownie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAgradecimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSonrisa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));

        buttonGroup1.add(rbCalcularTotal);
        rbCalcularTotal.setForeground(new java.awt.Color(255, 255, 255));
        rbCalcularTotal.setText("Calcular Total a Pagar");
        rbCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCalcularTotalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFinalizar);
        rbFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        rbFinalizar.setText("Finalizar");
        rbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFinalizarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbReset);
        rbReset.setForeground(new java.awt.Color(255, 255, 255));
        rbReset.setText("Reset");
        rbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbResetActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbCalcularTotal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbReset)
                            .addComponent(rbFinalizar))
                        .addGap(70, 70, 70)
                        .addComponent(txtTotal)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(rbCalcularTotal)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbReset)
                        .addGap(18, 18, 18)
                        .addComponent(rbFinalizar)))
                .addGap(65, 65, 65))
        );

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CAFETERÍA DONATELO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCalcularTotalActionPerformed
        // TODO add your handling code here:
        int TPagar = PMacchiato+PFrape+PTé+PCapuchino+PLate+PFrapuchino+PCroissant+PDona+PCheeseCake+PPayManzana+PBrownie+PFlan;
        
        if(TPagar != 0){
            txtTotal.setText("El precio total a pagar es de "+TPagar+"$");
        }else{
            txtTotal.setText("El precio a pagar es 0$ ya que no se ha ordenado nada");
        }
    }//GEN-LAST:event_rbCalcularTotalActionPerformed

    private void rbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFinalizarActionPerformed
        // TODO add your handling code here:
        Pant_Salida home = new Pant_Salida();
        home.setVisible(true);
    }//GEN-LAST:event_rbFinalizarActionPerformed

    private void chbMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMacchiatoActionPerformed
        // TODO add your handling code here:
        String macchiatotexto = JOptionPane.showInputDialog("Introduce el numero de macchiatos que desea comprar");
        int macchiato = Integer.parseInt(macchiatotexto);
        
        PMacchiato = 35 * macchiato;
    }//GEN-LAST:event_chbMacchiatoActionPerformed

    private void chbFrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFrapeActionPerformed
        // TODO add your handling code here:
        String frapetexto = JOptionPane.showInputDialog("Introduce el numero de frapes que desea comprar");
        int frape = Integer.parseInt(frapetexto);
        
        PFrape = 32 * frape;
    }//GEN-LAST:event_chbFrapeActionPerformed

    private void chbTéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTéActionPerformed
        // TODO add your handling code here:
        String tétexto = JOptionPane.showInputDialog("Introduce el numero de teés que desea comprar");
        int té = Integer.parseInt(tétexto);
        
        PTé = 20 * té;
    }//GEN-LAST:event_chbTéActionPerformed

    private void chbCapuchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCapuchinoActionPerformed
        // TODO add your handling code here:
        String capuchinotexto = JOptionPane.showInputDialog("Introduce el numero de capuchinos que desea comprar");
        int capuchino = Integer.parseInt(capuchinotexto);
        
        PCapuchino = 35 * capuchino;
    }//GEN-LAST:event_chbCapuchinoActionPerformed

    private void chbCaféLateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCaféLateActionPerformed
        // TODO add your handling code here:
        String latetexto = JOptionPane.showInputDialog("Introduce el numero de lates que desea comprar");
        int late = Integer.parseInt(latetexto);
        
        PLate = 35 * late;
    }//GEN-LAST:event_chbCaféLateActionPerformed

    private void chbFrapuchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFrapuchinoActionPerformed
        // TODO add your handling code here:
        String frapuchinotexto = JOptionPane.showInputDialog("Introduce el numero de frapuchinos que desea comprar");
        int frapuchino = Integer.parseInt(frapuchinotexto);
        
        PFrapuchino = 35 * frapuchino;
    }//GEN-LAST:event_chbFrapuchinoActionPerformed

    private void chbCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCroissantActionPerformed
        // TODO add your handling code here:
        String croissanttexto = JOptionPane.showInputDialog("Introduce el numero de croissants que desea comprar");
        int croissant = Integer.parseInt(croissanttexto);
        
        PCroissant = 30 * croissant;
    }//GEN-LAST:event_chbCroissantActionPerformed

    private void chbDonaConJaleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDonaConJaleaActionPerformed
        // TODO add your handling code here:
        String donatexto = JOptionPane.showInputDialog("Introduce el numero de teés que desea comprar");
        int dona = Integer.parseInt(donatexto);
        
        PDona = 25 * dona;
    }//GEN-LAST:event_chbDonaConJaleaActionPerformed

    private void chbCheeseCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCheeseCakeActionPerformed
        // TODO add your handling code here:
        String cheesecaketexto = JOptionPane.showInputDialog("Introduce el numero de teés que desea comprar");
        int cheesecake = Integer.parseInt(cheesecaketexto);
        
        PCheeseCake = 30 * cheesecake;
    }//GEN-LAST:event_chbCheeseCakeActionPerformed

    private void chbPayDeManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPayDeManzanaActionPerformed
        // TODO add your handling code here:
        String paymanzanatexto = JOptionPane.showInputDialog("Introduce el numero de teés que desea comprar");
        int paymanzana = Integer.parseInt(paymanzanatexto);
        
        PPayManzana = 25 * paymanzana;
    }//GEN-LAST:event_chbPayDeManzanaActionPerformed

    private void chbBrownieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbBrownieActionPerformed
        // TODO add your handling code here:
        String brownietexto = JOptionPane.showInputDialog("Introduce el numero de teés que desea comprar");
        int brownie = Integer.parseInt(brownietexto);
        
        PBrownie = 30 * brownie;
    }//GEN-LAST:event_chbBrownieActionPerformed

    private void chbFlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFlanActionPerformed
        // TODO add your handling code here:
        String flantexto = JOptionPane.showInputDialog("Introduce el numero de teés que desea comprar");
        int flan = Integer.parseInt(flantexto);
        
        PFlan = 15 * flan;
    }//GEN-LAST:event_chbFlanActionPerformed

    private void rbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbResetActionPerformed
        // TODO add your handling code here:
        txtTotal.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        PMacchiato = 0;
        PFrape = 0;
        PTé = 0;
        PCapuchino = 0;
        PLate = 0;
        PFrapuchino = 0;
    
        PCroissant = 0;
        PDona = 0;
        PCheeseCake = 0;
        PPayManzana = 0;
        PBrownie = 0;
        PFlan = 0;

        
        TPagar = 0;
    }//GEN-LAST:event_rbResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chbBrownie;
    private javax.swing.JCheckBox chbCaféLate;
    private javax.swing.JCheckBox chbCapuchino;
    private javax.swing.JCheckBox chbCheeseCake;
    private javax.swing.JCheckBox chbCroissant;
    private javax.swing.JCheckBox chbDonaConJalea;
    private javax.swing.JCheckBox chbFlan;
    private javax.swing.JCheckBox chbFrape;
    private javax.swing.JCheckBox chbFrapuchino;
    private javax.swing.JCheckBox chbMacchiato;
    private javax.swing.JCheckBox chbPayDeManzana;
    private javax.swing.JCheckBox chbTé;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAcompañamientos;
    private javax.swing.JLabel lblAgradecimiento;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblSonrisa;
    private javax.swing.JRadioButton rbCalcularTotal;
    private javax.swing.JRadioButton rbFinalizar;
    private javax.swing.JRadioButton rbReset;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
